In [1]:
import numpy as np

In [2]:
# synthetic data
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]]) # x is a matrix of size m*n where each row is a vector containing input features of a house 
y_train = np.array([460, 232, 178]) 

In [3]:
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [4]:
def predict(x, w, b):
    """
    x: vector
    w: vector
    b: scaler
    """
    p = np.dot(x, w) + b
    return p

In [5]:
def compute_cost(X, w, b, y):
    """
    this function's only use is to view how the cost changes as w and b change since we use its derivative to calculate the gradient not itself
    Args:
        X (ndarray (m,n)): Data, m examples with n features
        y (ndarray (m,)) : target values
        w (ndarray (n,)) : model parameters  
        b (scalar)       : model parameter
    Returns:
        cost (scaler)
    """
    m = x.shape[0]
    cost = 0.0
    for i in range(m):
        y_hat_i = predict(x[i], w, b)
        cost += (y_hat_i - y[i])**2
    cost = cost / (2 * m)
    return cost

In [17]:
def compute_gradient(X, w, b, y):
    """
    this function's only use is to view how the cost changes as w and b change since we use its derivative to calculate the gradient not itself
    Args:
        X (ndarray (m,n)): Data, m examples with n features
        y (ndarray (m,)) : target values
        w (ndarray (n,)) : model parameters  
        b (scalar)       : model parameter
    Returns:
        dj_dw (ndarray (n,)): The gradient of the cost w.r.t. the parameters w. 
        dj_db (scalar):       The gradient of the cost w.r.t. the parameter 
    """
    m,n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0
    for i in range(m):
        y_hat_i = predict(X[i], w, b)
        err = y_hat_i - y[i]
        for j in range(n): #loop over number of weights so you can find the gradient of cost w.r.t to each weight
            dj_dw[j] += err * X[i,j]
        dj_db += err
    dj_dw = dj_dw / m
    dj_db = dj_db / m
    return dj_dw, dj_db

In [18]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, w_init, b_init, y_train)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: [-2.72623581e-03 -6.27197272e-06 -2.21745580e-06 -6.92403399e-05]
dj_dw at initial w,b: 
 -1.673925169143331e-06


In [14]:
print(f"X_train shape: {X_train.shape}")
print(f"w_init shape: {w_init.shape}")

X_train shape: (3, 4)
w_init shape: (4,)
